export const GET_COUNCILS_REQUEST = "GET_COUNCILS_REQUEST";
export const GET_COUNCILS_SUCCESS = "GET_COUNCILS_SUCCESS";

export const GET_SINGLE_COUNCIL_SUCCESS = "GET_SINGLE_COUNCIL_SUCCESS";
export const GET_SINGLE_COUNCIL_REQUEST = "GET_SINGLE_COUNCIL_REQUEST";
