export const MEMBER_LIST_REQUEST = "MEMBER_LIST_REQUEST";
export const MEMBER_LIST_SUCCESS = "MEMBER_LIST_SUCCESS";
export const MEMBER_LIST_FAIL = "MEMBER_LIST_FAIL";

export const MEMBER_ADD_REQUEST = "MEMBER_ADD_REQUEST";
export const MEMBER_ADD_SUCCESS = "MEMBER_ADD_SUCCESS";
export const MEMBER_ADD_FAIL = "MEMBER_ADD_FAIL";
