export const GET_APC_OFFICERS_REQUEST = "GET_APC_OFFICERS_REQUEST";
export const GET_APC_OFFICERS_SUCCESS = "GET_APC_OFFICERS_SUCCESS";

export const CREATE_APC_OFFICERS_REQUEST = "CREATE_APC_OFFICERS_REQUEST";
export const CREATE_APC_OFFICERS_SUCCESS = "CREATE_APC_OFFICERS_SUCCESS";
export const CREATE_APC_OFFICERS_FAIL = "CREATE_APC_OFFICERS_FAIL";

export const GET_SINGLE_APC_OFFICERS_REQUESTS =
  "GET_SINGLE_APC_OFFICERS_REQUESTS";
export const GET_SINGLE_APC_OFFICERS_SUCCESS =
  "GET_SINGLE_APC_OFFICERS_SUCCESS";
export const GET_SINGLE_APC_OFFICERS_FAIL = "GET_SINGLE_APC_OFFICERS_FAIL";
